// Code generated by aru model:build from model.go. DO NOT EDIT.

package permission

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// GroupActions starts a query on the table of GroupAction, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func GroupActions(db model.DB) *GroupActionQuery {
	return &GroupActionQuery{b: groupActionTable.Query(db)}
}

// GroupActionQuery is a query on the table of GroupAction.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return GroupAction rows or a value; there is
// no way to run one without a Grant.
type GroupActionQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *GroupActionQuery) Base() *model.Builder { return q.b }

// New returns an empty GroupAction on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *GroupActionQuery) New() (*GroupAction, error) {
	e, err := q.b.NewModelInstance(nil)
	return groupActionOf(e), err
}

// GroupActionCollection is rows of GroupAction, as a query returns them.
type GroupActionCollection []*GroupAction

// GroupActionCollectionOf converts rows of the table of GroupAction. A nil input is a nil
// collection.
func GroupActionCollectionOf(rows model.Rows) GroupActionCollection {
	if rows == nil {
		return nil
	}
	out := make(GroupActionCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*GroupAction)
	}
	return out
}

func groupActionOf(e model.Entity) *GroupAction {
	row, _ := e.(*GroupAction)
	return row
}

// groupActionColumn turns a closure over GroupActionQuery into one over the core builder, so
// passing func(*GroupActionQuery) where a column goes adds a parenthesised group.
func groupActionColumn(column any) any {
	if group, ok := column.(func(*GroupActionQuery)); ok {
		return func(b *model.Builder) { group(&GroupActionQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *GroupActionQuery) Clone() *GroupActionQuery { return &GroupActionQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*GroupActionQuery) in place of the column adds a group.
func (q *GroupActionQuery) Where(column any, args ...any) *GroupActionQuery {
	q.b.Where(groupActionColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*GroupActionQuery) in place of the column adds a group.
func (q *GroupActionQuery) OrWhere(column any, args ...any) *GroupActionQuery {
	q.b.OrWhere(groupActionColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *GroupActionQuery) WhereNot(column any, args ...any) *GroupActionQuery {
	q.b.WhereNot(groupActionColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *GroupActionQuery) OrWhereNot(column any, args ...any) *GroupActionQuery {
	q.b.OrWhereNot(groupActionColumn(column), args...)
	return q
}

func (q *GroupActionQuery) WhereIn(column any, values []any) *GroupActionQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *GroupActionQuery) WhereNotIn(column any, values []any) *GroupActionQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *GroupActionQuery) WhereNull(columns ...any) *GroupActionQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *GroupActionQuery) WhereNotNull(columns ...any) *GroupActionQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *GroupActionQuery) WhereBetween(column any, from, to any) *GroupActionQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *GroupActionQuery) WhereColumn(first any, args ...any) *GroupActionQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *GroupActionQuery) WhereKey(id any) *GroupActionQuery {
	q.b.WhereKey(id)
	return q
}

func (q *GroupActionQuery) WhereExists(callback func(*query.Builder)) *GroupActionQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *GroupActionQuery) WhereNotExists(callback func(*query.Builder)) *GroupActionQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *GroupActionQuery) WhereHas(relation string, callback func(*query.Builder)) *GroupActionQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *GroupActionQuery) OrWhereHas(relation string, callback func(*query.Builder)) *GroupActionQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *GroupActionQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *GroupActionQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *GroupActionQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *GroupActionQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *GroupActionQuery) WhereRelation(relation string, column any, args ...any) *GroupActionQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *GroupActionQuery) OrWhereRelation(relation string, column any, args ...any) *GroupActionQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *GroupActionQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *GroupActionQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *GroupActionQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *GroupActionQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *GroupActionQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *GroupActionQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *GroupActionQuery) OrHas(relation, operator string, count int) *GroupActionQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *GroupActionQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *GroupActionQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *GroupActionQuery) OrDoesntHave(relation string) *GroupActionQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *GroupActionQuery) Select(columns ...any) *GroupActionQuery {
	q.b.Select(columns...)
	return q
}

func (q *GroupActionQuery) AddSelect(columns ...any) *GroupActionQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *GroupActionQuery) SelectRaw(expression string, bindings ...any) *GroupActionQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *GroupActionQuery) Join(table any, first any, args ...any) *GroupActionQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *GroupActionQuery) GroupBy(groups ...any) *GroupActionQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *GroupActionQuery) OrderBy(column any, direction ...string) *GroupActionQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *GroupActionQuery) OrderByDesc(column any) *GroupActionQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *GroupActionQuery) Latest(column ...string) *GroupActionQuery {
	q.b.Latest(column...)
	return q
}

func (q *GroupActionQuery) Oldest(column ...string) *GroupActionQuery {
	q.b.Oldest(column...)
	return q
}

func (q *GroupActionQuery) Limit(value int) *GroupActionQuery {
	q.b.Limit(value)
	return q
}

func (q *GroupActionQuery) Offset(value int) *GroupActionQuery {
	q.b.Offset(value)
	return q
}

func (q *GroupActionQuery) ForPage(page, perPage int) *GroupActionQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *GroupActionQuery) With(relations ...string) *GroupActionQuery {
	q.b.With(relations...)
	return q
}

func (q *GroupActionQuery) WithCount(relations ...string) *GroupActionQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *GroupActionQuery) WithExists(relation string) *GroupActionQuery {
	q.b.WithExists(relation)
	return q
}

func (q *GroupActionQuery) WithSum(relation, column string) *GroupActionQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *GroupActionQuery) WithAvg(relation, column string) *GroupActionQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *GroupActionQuery) WithMin(relation, column string) *GroupActionQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *GroupActionQuery) WithMax(relation, column string) *GroupActionQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *GroupActionQuery) Without(relations ...string) *GroupActionQuery {
	q.b.Without(relations...)
	return q
}

func (q *GroupActionQuery) WithoutGlobalScope(identifier string) *GroupActionQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *GroupActionQuery) WithoutGlobalScopes(identifiers ...string) *GroupActionQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *GroupActionQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (GroupActionCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return GroupActionCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *GroupActionQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*GroupAction, error) {
	e, err := q.b.First(ctx, g, columns...)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*GroupAction, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*GroupAction, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*GroupAction, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*GroupAction, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*GroupAction, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*GroupAction, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*GroupAction, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (GroupActionCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return GroupActionCollectionOf(rows), err
}

func (q *GroupActionQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*GroupAction, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*GroupAction, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*GroupAction, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*GroupAction, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return groupActionOf(e), err
}

func (q *GroupActionQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (GroupActionCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return GroupActionCollectionOf(rows), meta, err
}

func (q *GroupActionQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (GroupActionCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return GroupActionCollectionOf(rows), meta, err
}

func (q *GroupActionQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (GroupActionCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return GroupActionCollectionOf(rows), meta, err
}

func (q *GroupActionQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(GroupActionCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(GroupActionCollectionOf(rows), page)
	})
}

func (q *GroupActionQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*GroupAction, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(groupActionOf(e), index)
	})
}

func (q *GroupActionQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*GroupAction, error] {
	return func(yield func(*GroupAction, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(groupActionOf(e), err) {
				return
			}
		}
	}
}

func (q *GroupActionQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *GroupActionQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *GroupActionQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *GroupActionQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *GroupActionQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *GroupActionQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *GroupActionQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *GroupActionQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *GroupActionQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *GroupActionQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *GroupActionQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *GroupActionQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *GroupActionQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *GroupActionQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *GroupActionQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *GroupActionQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *GroupActionQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *GroupActionQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *GroupActionQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c GroupActionCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c GroupActionCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c GroupActionCollection) Find(key any) *GroupAction { return groupActionOf(c.Rows().Find(key)) }

func (c GroupActionCollection) FindOrFail(key any) (*GroupAction, error) {
	e, err := c.Rows().FindOrFail(key)
	return groupActionOf(e), err
}

func (c GroupActionCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c GroupActionCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c GroupActionCollection) Only(keys ...any) GroupActionCollection {
	return GroupActionCollectionOf(c.Rows().Only(keys...))
}

func (c GroupActionCollection) Except(keys ...any) GroupActionCollection {
	return GroupActionCollectionOf(c.Rows().Except(keys...))
}

func (c GroupActionCollection) Unique() GroupActionCollection {
	return GroupActionCollectionOf(c.Rows().Unique())
}

func (c GroupActionCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c GroupActionCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c GroupActionCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c GroupActionCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (GroupActionCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return GroupActionCollectionOf(rows), err
}

func (c GroupActionCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new GroupAction; it shadows the untyped one the
// embedded model promotes.
func (row *GroupAction) Fresh(ctx context.Context, g auth.Grant, with ...string) (*GroupAction, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return groupActionOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *GroupAction) Replicate(except ...string) (*GroupAction, error) {
	e, err := row.Model.Replicate(except...)
	return groupActionOf(e), err
}
