// Code generated by aru model:build from model.go. DO NOT EDIT.

package permission

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Groups starts a query on the table of Group, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Groups(db model.DB) *GroupQuery { return &GroupQuery{b: groupTable.Query(db)} }

// GroupQuery is a query on the table of Group.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Group rows or a value; there is
// no way to run one without a Grant.
type GroupQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *GroupQuery) Base() *model.Builder { return q.b }

// New returns an empty Group on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *GroupQuery) New() (*Group, error) {
	e, err := q.b.NewModelInstance(nil)
	return groupOf(e), err
}

// GroupCollection is rows of Group, as a query returns them.
type GroupCollection []*Group

// GroupCollectionOf converts rows of the table of Group. A nil input is a nil
// collection.
func GroupCollectionOf(rows model.Rows) GroupCollection {
	if rows == nil {
		return nil
	}
	out := make(GroupCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Group)
	}
	return out
}

func groupOf(e model.Entity) *Group {
	row, _ := e.(*Group)
	return row
}

// groupColumn turns a closure over GroupQuery into one over the core builder, so
// passing func(*GroupQuery) where a column goes adds a parenthesised group.
func groupColumn(column any) any {
	if group, ok := column.(func(*GroupQuery)); ok {
		return func(b *model.Builder) { group(&GroupQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *GroupQuery) Clone() *GroupQuery { return &GroupQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*GroupQuery) in place of the column adds a group.
func (q *GroupQuery) Where(column any, args ...any) *GroupQuery {
	q.b.Where(groupColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*GroupQuery) in place of the column adds a group.
func (q *GroupQuery) OrWhere(column any, args ...any) *GroupQuery {
	q.b.OrWhere(groupColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *GroupQuery) WhereNot(column any, args ...any) *GroupQuery {
	q.b.WhereNot(groupColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *GroupQuery) OrWhereNot(column any, args ...any) *GroupQuery {
	q.b.OrWhereNot(groupColumn(column), args...)
	return q
}

func (q *GroupQuery) WhereIn(column any, values []any) *GroupQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *GroupQuery) WhereNotIn(column any, values []any) *GroupQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *GroupQuery) WhereNull(columns ...any) *GroupQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *GroupQuery) WhereNotNull(columns ...any) *GroupQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *GroupQuery) WhereBetween(column any, from, to any) *GroupQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *GroupQuery) WhereColumn(first any, args ...any) *GroupQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *GroupQuery) WhereKey(id any) *GroupQuery {
	q.b.WhereKey(id)
	return q
}

func (q *GroupQuery) WhereExists(callback func(*query.Builder)) *GroupQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *GroupQuery) WhereNotExists(callback func(*query.Builder)) *GroupQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *GroupQuery) WhereHas(relation string, callback func(*query.Builder)) *GroupQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *GroupQuery) OrWhereHas(relation string, callback func(*query.Builder)) *GroupQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *GroupQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *GroupQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *GroupQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *GroupQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *GroupQuery) WhereRelation(relation string, column any, args ...any) *GroupQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *GroupQuery) OrWhereRelation(relation string, column any, args ...any) *GroupQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *GroupQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *GroupQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *GroupQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *GroupQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *GroupQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *GroupQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *GroupQuery) OrHas(relation, operator string, count int) *GroupQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *GroupQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *GroupQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *GroupQuery) OrDoesntHave(relation string) *GroupQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *GroupQuery) Select(columns ...any) *GroupQuery {
	q.b.Select(columns...)
	return q
}

func (q *GroupQuery) AddSelect(columns ...any) *GroupQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *GroupQuery) SelectRaw(expression string, bindings ...any) *GroupQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *GroupQuery) Join(table any, first any, args ...any) *GroupQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *GroupQuery) GroupBy(groups ...any) *GroupQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *GroupQuery) OrderBy(column any, direction ...string) *GroupQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *GroupQuery) OrderByDesc(column any) *GroupQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *GroupQuery) Latest(column ...string) *GroupQuery {
	q.b.Latest(column...)
	return q
}

func (q *GroupQuery) Oldest(column ...string) *GroupQuery {
	q.b.Oldest(column...)
	return q
}

func (q *GroupQuery) Limit(value int) *GroupQuery {
	q.b.Limit(value)
	return q
}

func (q *GroupQuery) Offset(value int) *GroupQuery {
	q.b.Offset(value)
	return q
}

func (q *GroupQuery) ForPage(page, perPage int) *GroupQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *GroupQuery) With(relations ...string) *GroupQuery {
	q.b.With(relations...)
	return q
}

func (q *GroupQuery) WithCount(relations ...string) *GroupQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *GroupQuery) WithExists(relation string) *GroupQuery {
	q.b.WithExists(relation)
	return q
}

func (q *GroupQuery) WithSum(relation, column string) *GroupQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *GroupQuery) WithAvg(relation, column string) *GroupQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *GroupQuery) WithMin(relation, column string) *GroupQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *GroupQuery) WithMax(relation, column string) *GroupQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *GroupQuery) Without(relations ...string) *GroupQuery {
	q.b.Without(relations...)
	return q
}

func (q *GroupQuery) WithoutGlobalScope(identifier string) *GroupQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *GroupQuery) WithoutGlobalScopes(identifiers ...string) *GroupQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *GroupQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (GroupCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return GroupCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *GroupQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Group, error) {
	e, err := q.b.First(ctx, g, columns...)
	return groupOf(e), err
}

func (q *GroupQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Group, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return groupOf(e), err
}

func (q *GroupQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Group, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return groupOf(e), err
}

func (q *GroupQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Group, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return groupOf(e), err
}

func (q *GroupQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Group, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return groupOf(e), err
}

func (q *GroupQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Group, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return groupOf(e), err
}

func (q *GroupQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Group, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return groupOf(e), err
}

func (q *GroupQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Group, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return groupOf(e), err
}

func (q *GroupQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (GroupCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return GroupCollectionOf(rows), err
}

func (q *GroupQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Group, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return groupOf(e), err
}

func (q *GroupQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Group, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return groupOf(e), err
}

func (q *GroupQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Group, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return groupOf(e), err
}

func (q *GroupQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Group, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return groupOf(e), err
}

func (q *GroupQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (GroupCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return GroupCollectionOf(rows), meta, err
}

func (q *GroupQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (GroupCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return GroupCollectionOf(rows), meta, err
}

func (q *GroupQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (GroupCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return GroupCollectionOf(rows), meta, err
}

func (q *GroupQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(GroupCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(GroupCollectionOf(rows), page)
	})
}

func (q *GroupQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Group, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(groupOf(e), index)
	})
}

func (q *GroupQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Group, error] {
	return func(yield func(*Group, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(groupOf(e), err) {
				return
			}
		}
	}
}

func (q *GroupQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *GroupQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *GroupQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *GroupQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *GroupQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *GroupQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *GroupQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *GroupQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *GroupQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *GroupQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *GroupQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *GroupQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *GroupQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *GroupQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *GroupQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *GroupQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *GroupQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *GroupQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *GroupQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c GroupCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c GroupCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c GroupCollection) Find(key any) *Group { return groupOf(c.Rows().Find(key)) }

func (c GroupCollection) FindOrFail(key any) (*Group, error) {
	e, err := c.Rows().FindOrFail(key)
	return groupOf(e), err
}

func (c GroupCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c GroupCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c GroupCollection) Only(keys ...any) GroupCollection {
	return GroupCollectionOf(c.Rows().Only(keys...))
}

func (c GroupCollection) Except(keys ...any) GroupCollection {
	return GroupCollectionOf(c.Rows().Except(keys...))
}

func (c GroupCollection) Unique() GroupCollection { return GroupCollectionOf(c.Rows().Unique()) }

func (c GroupCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c GroupCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c GroupCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c GroupCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (GroupCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return GroupCollectionOf(rows), err
}

func (c GroupCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Group; it shadows the untyped one the
// embedded model promotes.
func (row *Group) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Group, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return groupOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Group) Replicate(except ...string) (*Group, error) {
	e, err := row.Model.Replicate(except...)
	return groupOf(e), err
}
