// Code generated by aru model:build from model.go. DO NOT EDIT.

package permission

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// GroupUsers starts a query on the table of GroupUser, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func GroupUsers(db model.DB) *GroupUserQuery { return &GroupUserQuery{b: groupUserTable.Query(db)} }

// GroupUserQuery is a query on the table of GroupUser.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return GroupUser rows or a value; there is
// no way to run one without a Grant.
type GroupUserQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *GroupUserQuery) Base() *model.Builder { return q.b }

// New returns an empty GroupUser on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *GroupUserQuery) New() (*GroupUser, error) {
	e, err := q.b.NewModelInstance(nil)
	return groupUserOf(e), err
}

// GroupUserCollection is rows of GroupUser, as a query returns them.
type GroupUserCollection []*GroupUser

// GroupUserCollectionOf converts rows of the table of GroupUser. A nil input is a nil
// collection.
func GroupUserCollectionOf(rows model.Rows) GroupUserCollection {
	if rows == nil {
		return nil
	}
	out := make(GroupUserCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*GroupUser)
	}
	return out
}

func groupUserOf(e model.Entity) *GroupUser {
	row, _ := e.(*GroupUser)
	return row
}

// groupUserColumn turns a closure over GroupUserQuery into one over the core builder, so
// passing func(*GroupUserQuery) where a column goes adds a parenthesised group.
func groupUserColumn(column any) any {
	if group, ok := column.(func(*GroupUserQuery)); ok {
		return func(b *model.Builder) { group(&GroupUserQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *GroupUserQuery) Clone() *GroupUserQuery { return &GroupUserQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*GroupUserQuery) in place of the column adds a group.
func (q *GroupUserQuery) Where(column any, args ...any) *GroupUserQuery {
	q.b.Where(groupUserColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*GroupUserQuery) in place of the column adds a group.
func (q *GroupUserQuery) OrWhere(column any, args ...any) *GroupUserQuery {
	q.b.OrWhere(groupUserColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *GroupUserQuery) WhereNot(column any, args ...any) *GroupUserQuery {
	q.b.WhereNot(groupUserColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *GroupUserQuery) OrWhereNot(column any, args ...any) *GroupUserQuery {
	q.b.OrWhereNot(groupUserColumn(column), args...)
	return q
}

func (q *GroupUserQuery) WhereIn(column any, values []any) *GroupUserQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *GroupUserQuery) WhereNotIn(column any, values []any) *GroupUserQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *GroupUserQuery) WhereNull(columns ...any) *GroupUserQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *GroupUserQuery) WhereNotNull(columns ...any) *GroupUserQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *GroupUserQuery) WhereBetween(column any, from, to any) *GroupUserQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *GroupUserQuery) WhereColumn(first any, args ...any) *GroupUserQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *GroupUserQuery) WhereKey(id any) *GroupUserQuery {
	q.b.WhereKey(id)
	return q
}

func (q *GroupUserQuery) WhereExists(callback func(*query.Builder)) *GroupUserQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *GroupUserQuery) WhereNotExists(callback func(*query.Builder)) *GroupUserQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *GroupUserQuery) WhereHas(relation string, callback func(*query.Builder)) *GroupUserQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *GroupUserQuery) OrWhereHas(relation string, callback func(*query.Builder)) *GroupUserQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *GroupUserQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *GroupUserQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *GroupUserQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *GroupUserQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *GroupUserQuery) WhereRelation(relation string, column any, args ...any) *GroupUserQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *GroupUserQuery) OrWhereRelation(relation string, column any, args ...any) *GroupUserQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *GroupUserQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *GroupUserQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *GroupUserQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *GroupUserQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *GroupUserQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *GroupUserQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *GroupUserQuery) OrHas(relation, operator string, count int) *GroupUserQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *GroupUserQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *GroupUserQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *GroupUserQuery) OrDoesntHave(relation string) *GroupUserQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *GroupUserQuery) Select(columns ...any) *GroupUserQuery {
	q.b.Select(columns...)
	return q
}

func (q *GroupUserQuery) AddSelect(columns ...any) *GroupUserQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *GroupUserQuery) SelectRaw(expression string, bindings ...any) *GroupUserQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *GroupUserQuery) Join(table any, first any, args ...any) *GroupUserQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *GroupUserQuery) GroupBy(groups ...any) *GroupUserQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *GroupUserQuery) OrderBy(column any, direction ...string) *GroupUserQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *GroupUserQuery) OrderByDesc(column any) *GroupUserQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *GroupUserQuery) Latest(column ...string) *GroupUserQuery {
	q.b.Latest(column...)
	return q
}

func (q *GroupUserQuery) Oldest(column ...string) *GroupUserQuery {
	q.b.Oldest(column...)
	return q
}

func (q *GroupUserQuery) Limit(value int) *GroupUserQuery {
	q.b.Limit(value)
	return q
}

func (q *GroupUserQuery) Offset(value int) *GroupUserQuery {
	q.b.Offset(value)
	return q
}

func (q *GroupUserQuery) ForPage(page, perPage int) *GroupUserQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *GroupUserQuery) With(relations ...string) *GroupUserQuery {
	q.b.With(relations...)
	return q
}

func (q *GroupUserQuery) WithCount(relations ...string) *GroupUserQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *GroupUserQuery) WithExists(relation string) *GroupUserQuery {
	q.b.WithExists(relation)
	return q
}

func (q *GroupUserQuery) WithSum(relation, column string) *GroupUserQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *GroupUserQuery) WithAvg(relation, column string) *GroupUserQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *GroupUserQuery) WithMin(relation, column string) *GroupUserQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *GroupUserQuery) WithMax(relation, column string) *GroupUserQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *GroupUserQuery) Without(relations ...string) *GroupUserQuery {
	q.b.Without(relations...)
	return q
}

func (q *GroupUserQuery) WithoutGlobalScope(identifier string) *GroupUserQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *GroupUserQuery) WithoutGlobalScopes(identifiers ...string) *GroupUserQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *GroupUserQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (GroupUserCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return GroupUserCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *GroupUserQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*GroupUser, error) {
	e, err := q.b.First(ctx, g, columns...)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*GroupUser, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*GroupUser, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*GroupUser, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*GroupUser, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*GroupUser, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*GroupUser, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*GroupUser, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (GroupUserCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return GroupUserCollectionOf(rows), err
}

func (q *GroupUserQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*GroupUser, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*GroupUser, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*GroupUser, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*GroupUser, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return groupUserOf(e), err
}

func (q *GroupUserQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (GroupUserCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return GroupUserCollectionOf(rows), meta, err
}

func (q *GroupUserQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (GroupUserCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return GroupUserCollectionOf(rows), meta, err
}

func (q *GroupUserQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (GroupUserCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return GroupUserCollectionOf(rows), meta, err
}

func (q *GroupUserQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(GroupUserCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(GroupUserCollectionOf(rows), page)
	})
}

func (q *GroupUserQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*GroupUser, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(groupUserOf(e), index)
	})
}

func (q *GroupUserQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*GroupUser, error] {
	return func(yield func(*GroupUser, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(groupUserOf(e), err) {
				return
			}
		}
	}
}

func (q *GroupUserQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *GroupUserQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *GroupUserQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *GroupUserQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *GroupUserQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *GroupUserQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *GroupUserQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *GroupUserQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *GroupUserQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *GroupUserQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *GroupUserQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *GroupUserQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *GroupUserQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *GroupUserQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *GroupUserQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *GroupUserQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *GroupUserQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *GroupUserQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *GroupUserQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c GroupUserCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c GroupUserCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c GroupUserCollection) Find(key any) *GroupUser { return groupUserOf(c.Rows().Find(key)) }

func (c GroupUserCollection) FindOrFail(key any) (*GroupUser, error) {
	e, err := c.Rows().FindOrFail(key)
	return groupUserOf(e), err
}

func (c GroupUserCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c GroupUserCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c GroupUserCollection) Only(keys ...any) GroupUserCollection {
	return GroupUserCollectionOf(c.Rows().Only(keys...))
}

func (c GroupUserCollection) Except(keys ...any) GroupUserCollection {
	return GroupUserCollectionOf(c.Rows().Except(keys...))
}

func (c GroupUserCollection) Unique() GroupUserCollection {
	return GroupUserCollectionOf(c.Rows().Unique())
}

func (c GroupUserCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c GroupUserCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c GroupUserCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c GroupUserCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (GroupUserCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return GroupUserCollectionOf(rows), err
}

func (c GroupUserCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new GroupUser; it shadows the untyped one the
// embedded model promotes.
func (row *GroupUser) Fresh(ctx context.Context, g auth.Grant, with ...string) (*GroupUser, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return groupUserOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *GroupUser) Replicate(except ...string) (*GroupUser, error) {
	e, err := row.Model.Replicate(except...)
	return groupUserOf(e), err
}
