package permission

import (
	"errors"
	"time"

	"github.com/arandu-io/framework/data"
	"github.com/arandu-io/framework/security"
	"github.com/arandu-io/hesape/database/model"
)

// The tables this package owns.
//
// They are named here once and read from here everywhere, so the migration, the
// models and anything that inspects the schema cannot drift into two spellings
// of one table.
const (
	// GroupsTable holds one row per group.
	GroupsTable = "permission_groups"
	// GroupActionsTable holds one row per action a group carries.
	GroupActionsTable = "permission_group_actions"
	// GroupUsersTable holds one row per person in a group.
	GroupUsersTable = "permission_group_users"
	// UserActionsTable holds one row per action a person carries outside every
	// group.
	UserActionsTable = "permission_user_actions"
	// VersionsTable holds one row per tenant, carrying the token that changes
	// whenever anything above does.
	VersionsTable = "permission_versions"
)

// Group is a named set of actions, and the people who carry them.
//
// It embeds the model, so a row returned by a query carries the connection and
// can be saved again. Build new rows through Groups: a struct literal has no
// connection and its write methods return model.ErrUnwired.
type Group struct {
	model.Model[Group]

	// ID is the identifier. It is generated by the application rather than by
	// the database, because a DEFAULT that produces a uuid is spelled
	// differently in every engine.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to. It is written from the
	// Grant and read back so the policy can compare it against the subject's
	// tenant.
	TenantID string `db:"tenant_id"`

	// Slug is the stable, lowercase name of the group inside its tenant. It is
	// what a seed and a migration name a group by, and it does not change:
	// renaming it would silently create a second group beside whatever already
	// referred to the first.
	Slug string `db:"slug"`

	// Name is what a person calls this group, and Description is why it exists.
	// Both are free text, both are editable, and neither is ever compared
	// against anything.
	Name        string `db:"name"`
	Description string `db:"description"`

	// IsSystem marks a group the installation depends on. It cannot be deleted
	// and its actions cannot be detached, because it is the group that carries
	// the administration of permissions: an application that emptied it would
	// have nobody left who could fill it again.
	IsSystem bool `db:"is_system"`

	// CreatedAt and UpdatedAt are when the row was written and last changed, in
	// UTC.
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

// Groups returns the configured model for the groups table.
//
// The primary key is application-generated text, so it does not increment. The
// tenant scope remains on the model's tenant_id default.
func Groups(db *data.DB) *model.Model[Group] {
	m := model.NewModel[Group](GroupsTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// GroupAction is one action a group carries.
//
// Action is a plain string and not the action type the policies take, because
// the column is read and written by the driver: a named type is one more thing
// between what the database holds and what compares it. It is converted at the
// two edges that care, and the conversion is checked against the catalogue
// before anything is written.
type GroupAction struct {
	model.Model[GroupAction]

	// ID is the identifier, generated by the application.
	ID string `db:"id"`
	// TenantID is the customer the row belongs to.
	TenantID string `db:"tenant_id"`
	// GroupID is the group this row attaches the action to.
	GroupID string `db:"group_id"`
	// Action is the action, in module.verb form, and it exists in the
	// catalogue: nothing writes this column without checking that first.
	Action string `db:"action"`
}

// GroupActions returns the configured model for the group actions table.
//
// It keeps no timestamps: the row is the link and nothing else, and a column
// that is written and never read is a column somebody eventually filters by.
func GroupActions(db *data.DB) *model.Model[GroupAction] {
	m := model.NewModel[GroupAction](GroupActionsTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	m.Timestamps = false
	return m
}

// GroupUser is one person in a group.
type GroupUser struct {
	model.Model[GroupUser]

	// ID is the identifier, generated by the application.
	ID string `db:"id"`
	// TenantID is the customer the row belongs to.
	TenantID string `db:"tenant_id"`
	// GroupID is the group, and UserID is who is in it.
	GroupID string `db:"group_id"`
	UserID  string `db:"user_id"`
}

// GroupUsers returns the configured model for the group members table.
//
// It keeps no timestamps, for the reason GroupActions keeps none.
func GroupUsers(db *data.DB) *model.Model[GroupUser] {
	m := model.NewModel[GroupUser](GroupUsersTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	m.Timestamps = false
	return m
}

// UserAction is one action a person carries in their own right.
//
// It is the grant that belongs to nobody else: a group is the answer to "what do
// people like this do", and this is the answer to "and this one person also does
// that". The reference calls them extra permissions, and the word is right --
// they are what a person holds on top of whatever their groups confer.
//
// It is not a second way to authorize. The action is checked against the same
// catalogue, it lands in the same resolved set the middleware puts on the
// subject, and the same policy in Go decides with it. What it adds is one more
// place the set is read from, before anything decides anything.
//
// It is the shortest path to more power there is, which is why the policy that
// answers about it refuses the two moves that matter: handing out what you do
// not hold, and handing anything to yourself.
type UserAction struct {
	model.Model[UserAction]

	// ID is the identifier, generated by the application.
	ID string `db:"id"`
	// TenantID is the customer the row belongs to.
	TenantID string `db:"tenant_id"`
	// UserID is who carries it.
	UserID string `db:"user_id"`
	// Action is the action, in module.verb form, and it exists in the
	// catalogue: nothing writes this column without checking that first.
	Action string `db:"action"`
}

// UserActions returns the configured model for the direct grants table.
//
// It keeps no timestamps, for the reason GroupActions keeps none.
func UserActions(db *data.DB) *model.Model[UserAction] {
	m := model.NewModel[UserAction](UserActionsTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	m.Timestamps = false
	return m
}

// Version is the token that changes whenever a tenant's permissions do.
//
// One row per tenant, keyed by the tenant, so reading it is a point read on the
// primary key and writing it cannot produce a second row for the same customer.
//
// The value is compared for equality and never ordered. It is not a count of
// changes and nothing may read it as one: two changes at once have to produce
// two different tokens, and a counter incremented from the same starting value
// twice produces one.
type Version struct {
	model.Model[Version]

	// TenantID is the customer, and the primary key.
	TenantID string `db:"tenant_id"`
	// Version is the token.
	Version int64 `db:"version"`
}

// Versions returns the configured model for the version table.
//
// Its key is the tenant column, which is the one place in this package where
// the two are the same: the table holds one row per customer, so the scope and
// the key are one question.
func Versions(db *data.DB) *model.Model[Version] {
	m := model.NewModel[Version](VersionsTable, db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.PrimaryKey = "tenant_id"
	m.KeyType = "string"
	m.Incrementing = false
	m.Timestamps = false
	return m
}

// The refusals this package answers with.
//
// They are distinguished from one another because they are answered with
// different statuses and because only one of them is the caller's fault.
var (
	// ErrNotFound is returned when no row matches, including when the row
	// exists in another tenant. The two cases are deliberately
	// indistinguishable.
	ErrNotFound = errors.New("permission: record not found")

	// ErrUnknownAction is returned when an action is not in the catalogue. It
	// is what makes a group unable to carry a permission no policy reads.
	ErrUnknownAction = errors.New("permission: the action is not in the catalogue")

	// ErrLastMember is returned when taking somebody out of a system group
	// would leave it empty.
	//
	// It is not an authorization refusal and is deliberately not spelled as
	// one: the subject was allowed to do it, and the state it would leave
	// behind is what is refused. An application that answered it as 403 would
	// tell somebody to ask for a permission they already have.
	ErrLastMember = errors.New("permission: a system group cannot be left without a member")

	// ErrSlugTaken is returned when a group with that slug already exists in
	// the tenant.
	ErrSlugTaken = errors.New("permission: a group with this slug already exists")

	// ErrTooMany is returned when one write names more actions or more people
	// than a request may.
	//
	// It is the caller's fault and it is answered as such. It used to be an
	// unnamed error, which meant a client that sent one too many was told the
	// server had failed -- and a person who reads that sends it again.
	ErrTooMany = errors.New("permission: the write names more than one request may")

	// ErrInvalidMember is returned when somebody is named by an identifier that
	// cannot be one.
	ErrInvalidMember = errors.New("permission: a member was named by an identifier that cannot be one")

	// ErrBootstrapped is returned when the first group is asked for and the
	// tenant already has one.
	//
	// It is what closes the only door in this package that opens without a
	// subject behind it. The door exists because nobody can administer
	// permissions until somebody carries them; it shuts the moment somebody
	// does, and it never opens again.
	ErrBootstrapped = errors.New("permission: this tenant already has a group, so there is somebody to authorize as")
)

// GroupRef is a group as something else refers to it: enough to name it on a
// screen, and no more.
type GroupRef struct {
	// ID addresses the group, Slug identifies it and Name is what a person
	// reads.
	ID   string
	Slug string
	Name string
}

// EffectiveGrant is one action a person holds, and everything that gives it to
// them.
//
// The origin is a list and not a single group, because two groups granting the
// same action is the normal case and the question a screen is asked is "why do
// they have this" -- which has as many answers as there are groups.
//
// Direct is the answer that is not a group at all, and it is a separate field
// rather than a group with a made-up name: a screen that listed it beside the
// real ones would offer a link to a group that does not exist, and whoever
// wanted to take the permission away would go looking for it there.
type EffectiveGrant struct {
	// Action is what the person may do.
	Action security.Action
	// Groups are the groups that grant it, sorted by slug.
	Groups []GroupRef
	// Direct is whether the person carries it in their own right, on top of
	// whatever the groups confer.
	Direct bool
}

// Effective is what one person may do, and why.
type Effective struct {
	// UserID is who this is about.
	UserID string
	// Grants are the actions they hold, sorted by action.
	Grants []EffectiveGrant
	// Groups are the groups they belong to, sorted by slug.
	Groups []GroupRef
	// Direct are the actions they carry in their own right, sorted. They are
	// also in Grants, marked as such; this is the list a screen edits.
	Direct []security.Action
}

// Actions is the flat list an authorization decision reads: one entry per
// distinct action, sorted.
//
// It was called Roles and answered []string, because auth.Subject had one list
// of strings and Roles was its name. Writing actions into that field made
// HasRole answer about them -- so every policy in a consuming application that
// asked HasRole("admin") began answering false, silently, since both sides were
// []string. Subject carries Actions now, typed, and this is what fills it.
func (e Effective) Actions() []security.Action {
	out := make([]security.Action, 0, len(e.Grants))
	for _, grant := range e.Grants {
		out = append(out, grant.Action)
	}
	return out
}

// MemberRef is one person as a listing names them: who they are, what puts them
// there, and nothing else.
//
// There is no name and no address on it, and there cannot be. This package does
// not own the table people are in -- it owns rows about them -- so a listing here
// answers "who has this module written something about", which is a different
// question from "who are the users" and is the only one it can answer honestly.
// An application that wants names joins these identifiers to its own table.
type MemberRef struct {
	// UserID is who this is about.
	UserID string
	// Groups are the groups they are in, sorted by slug.
	Groups []GroupRef
	// Direct is how many permissions they carry in their own right. It is a
	// count and not the list, because the listing is one line per person and a
	// person with forty of them would be forty lines.
	Direct int
}

// MemberQuery is what a listing of people asks for.
type MemberQuery struct {
	// Group narrows the listing to one group, by slug. Empty is everybody.
	Group string
	// Cursor is where this page resumes, taken from the previous page's Next.
	Cursor string
	// Limit is how many people the page holds. Zero means the default, and
	// anything above the maximum is brought down to it.
	Limit int
}

// MemberPage is a page of people and where the next one resumes.
type MemberPage struct {
	// Items are the people, in identifier order.
	Items []MemberRef
	// Next is what the next request passes back as a cursor, empty when this
	// page is the last one.
	Next string
}

// GroupPage is a page of groups and where the next one resumes.
type GroupPage struct {
	// Items are the groups, in slug order.
	Items []GroupRef
	// Next is what the next request passes back as a cursor, empty when this
	// page is the last one.
	Next string
}

// Change is what a bulk write would do, or did.
//
// It is returned by the preview and by the write, from the same computation, so
// the summary somebody approved is the summary that was applied rather than a
// second reading of the same intent.
type Change struct {
	// Added and Removed are what the write puts in and takes out, sorted.
	// Unchanged is what was already as asked, which is what makes the summary
	// readable: a list of twelve permissions where two are changing says more
	// than a list of two.
	Added     []string
	Removed   []string
	Unchanged []string
}

// Empty reports whether the change would write nothing.
func (c Change) Empty() bool { return len(c.Added) == 0 && len(c.Removed) == 0 }
