// Code generated by aru model:build from model.go. DO NOT EDIT.

package permission

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// UserActions starts a query on the table of UserAction, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func UserActions(db model.DB) *UserActionQuery { return &UserActionQuery{b: userActionTable.Query(db)} }

// UserActionQuery is a query on the table of UserAction.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return UserAction rows or a value; there is
// no way to run one without a Grant.
type UserActionQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *UserActionQuery) Base() *model.Builder { return q.b }

// New returns an empty UserAction on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *UserActionQuery) New() (*UserAction, error) {
	e, err := q.b.NewModelInstance(nil)
	return userActionOf(e), err
}

// UserActionCollection is rows of UserAction, as a query returns them.
type UserActionCollection []*UserAction

// UserActionCollectionOf converts rows of the table of UserAction. A nil input is a nil
// collection.
func UserActionCollectionOf(rows model.Rows) UserActionCollection {
	if rows == nil {
		return nil
	}
	out := make(UserActionCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*UserAction)
	}
	return out
}

func userActionOf(e model.Entity) *UserAction {
	row, _ := e.(*UserAction)
	return row
}

// userActionColumn turns a closure over UserActionQuery into one over the core builder, so
// passing func(*UserActionQuery) where a column goes adds a parenthesised group.
func userActionColumn(column any) any {
	if group, ok := column.(func(*UserActionQuery)); ok {
		return func(b *model.Builder) { group(&UserActionQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *UserActionQuery) Clone() *UserActionQuery { return &UserActionQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*UserActionQuery) in place of the column adds a group.
func (q *UserActionQuery) Where(column any, args ...any) *UserActionQuery {
	q.b.Where(userActionColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*UserActionQuery) in place of the column adds a group.
func (q *UserActionQuery) OrWhere(column any, args ...any) *UserActionQuery {
	q.b.OrWhere(userActionColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *UserActionQuery) WhereNot(column any, args ...any) *UserActionQuery {
	q.b.WhereNot(userActionColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *UserActionQuery) OrWhereNot(column any, args ...any) *UserActionQuery {
	q.b.OrWhereNot(userActionColumn(column), args...)
	return q
}

func (q *UserActionQuery) WhereIn(column any, values []any) *UserActionQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *UserActionQuery) WhereNotIn(column any, values []any) *UserActionQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *UserActionQuery) WhereNull(columns ...any) *UserActionQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *UserActionQuery) WhereNotNull(columns ...any) *UserActionQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *UserActionQuery) WhereBetween(column any, from, to any) *UserActionQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *UserActionQuery) WhereColumn(first any, args ...any) *UserActionQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *UserActionQuery) WhereKey(id any) *UserActionQuery {
	q.b.WhereKey(id)
	return q
}

func (q *UserActionQuery) WhereExists(callback func(*query.Builder)) *UserActionQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *UserActionQuery) WhereNotExists(callback func(*query.Builder)) *UserActionQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *UserActionQuery) WhereHas(relation string, callback func(*query.Builder)) *UserActionQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *UserActionQuery) OrWhereHas(relation string, callback func(*query.Builder)) *UserActionQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *UserActionQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *UserActionQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *UserActionQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *UserActionQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *UserActionQuery) WhereRelation(relation string, column any, args ...any) *UserActionQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *UserActionQuery) OrWhereRelation(relation string, column any, args ...any) *UserActionQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *UserActionQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *UserActionQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *UserActionQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *UserActionQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *UserActionQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *UserActionQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *UserActionQuery) OrHas(relation, operator string, count int) *UserActionQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *UserActionQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *UserActionQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *UserActionQuery) OrDoesntHave(relation string) *UserActionQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *UserActionQuery) Select(columns ...any) *UserActionQuery {
	q.b.Select(columns...)
	return q
}

func (q *UserActionQuery) AddSelect(columns ...any) *UserActionQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *UserActionQuery) SelectRaw(expression string, bindings ...any) *UserActionQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *UserActionQuery) Join(table any, first any, args ...any) *UserActionQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *UserActionQuery) GroupBy(groups ...any) *UserActionQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *UserActionQuery) OrderBy(column any, direction ...string) *UserActionQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *UserActionQuery) OrderByDesc(column any) *UserActionQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *UserActionQuery) Latest(column ...string) *UserActionQuery {
	q.b.Latest(column...)
	return q
}

func (q *UserActionQuery) Oldest(column ...string) *UserActionQuery {
	q.b.Oldest(column...)
	return q
}

func (q *UserActionQuery) Limit(value int) *UserActionQuery {
	q.b.Limit(value)
	return q
}

func (q *UserActionQuery) Offset(value int) *UserActionQuery {
	q.b.Offset(value)
	return q
}

func (q *UserActionQuery) ForPage(page, perPage int) *UserActionQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *UserActionQuery) With(relations ...string) *UserActionQuery {
	q.b.With(relations...)
	return q
}

func (q *UserActionQuery) WithCount(relations ...string) *UserActionQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *UserActionQuery) WithExists(relation string) *UserActionQuery {
	q.b.WithExists(relation)
	return q
}

func (q *UserActionQuery) WithSum(relation, column string) *UserActionQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *UserActionQuery) WithAvg(relation, column string) *UserActionQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *UserActionQuery) WithMin(relation, column string) *UserActionQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *UserActionQuery) WithMax(relation, column string) *UserActionQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *UserActionQuery) Without(relations ...string) *UserActionQuery {
	q.b.Without(relations...)
	return q
}

func (q *UserActionQuery) WithoutGlobalScope(identifier string) *UserActionQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *UserActionQuery) WithoutGlobalScopes(identifiers ...string) *UserActionQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *UserActionQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (UserActionCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return UserActionCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *UserActionQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*UserAction, error) {
	e, err := q.b.First(ctx, g, columns...)
	return userActionOf(e), err
}

func (q *UserActionQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*UserAction, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return userActionOf(e), err
}

func (q *UserActionQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*UserAction, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return userActionOf(e), err
}

func (q *UserActionQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*UserAction, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return userActionOf(e), err
}

func (q *UserActionQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*UserAction, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return userActionOf(e), err
}

func (q *UserActionQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*UserAction, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return userActionOf(e), err
}

func (q *UserActionQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*UserAction, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return userActionOf(e), err
}

func (q *UserActionQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*UserAction, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return userActionOf(e), err
}

func (q *UserActionQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (UserActionCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return UserActionCollectionOf(rows), err
}

func (q *UserActionQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*UserAction, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return userActionOf(e), err
}

func (q *UserActionQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*UserAction, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return userActionOf(e), err
}

func (q *UserActionQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*UserAction, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return userActionOf(e), err
}

func (q *UserActionQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*UserAction, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return userActionOf(e), err
}

func (q *UserActionQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (UserActionCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return UserActionCollectionOf(rows), meta, err
}

func (q *UserActionQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (UserActionCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return UserActionCollectionOf(rows), meta, err
}

func (q *UserActionQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (UserActionCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return UserActionCollectionOf(rows), meta, err
}

func (q *UserActionQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(UserActionCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(UserActionCollectionOf(rows), page)
	})
}

func (q *UserActionQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*UserAction, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(userActionOf(e), index)
	})
}

func (q *UserActionQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*UserAction, error] {
	return func(yield func(*UserAction, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(userActionOf(e), err) {
				return
			}
		}
	}
}

func (q *UserActionQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *UserActionQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *UserActionQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *UserActionQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *UserActionQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *UserActionQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *UserActionQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *UserActionQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *UserActionQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *UserActionQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *UserActionQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *UserActionQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *UserActionQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *UserActionQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *UserActionQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *UserActionQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *UserActionQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *UserActionQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *UserActionQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c UserActionCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c UserActionCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c UserActionCollection) Find(key any) *UserAction { return userActionOf(c.Rows().Find(key)) }

func (c UserActionCollection) FindOrFail(key any) (*UserAction, error) {
	e, err := c.Rows().FindOrFail(key)
	return userActionOf(e), err
}

func (c UserActionCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c UserActionCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c UserActionCollection) Only(keys ...any) UserActionCollection {
	return UserActionCollectionOf(c.Rows().Only(keys...))
}

func (c UserActionCollection) Except(keys ...any) UserActionCollection {
	return UserActionCollectionOf(c.Rows().Except(keys...))
}

func (c UserActionCollection) Unique() UserActionCollection {
	return UserActionCollectionOf(c.Rows().Unique())
}

func (c UserActionCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c UserActionCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c UserActionCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c UserActionCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (UserActionCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return UserActionCollectionOf(rows), err
}

func (c UserActionCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new UserAction; it shadows the untyped one the
// embedded model promotes.
func (row *UserAction) Fresh(ctx context.Context, g auth.Grant, with ...string) (*UserAction, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return userActionOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *UserAction) Replicate(except ...string) (*UserAction, error) {
	e, err := row.Model.Replicate(except...)
	return userActionOf(e), err
}
