// Code generated by aru model:build from model.go. DO NOT EDIT.

package permission

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Versions starts a query on the table of Version, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Versions(db model.DB) *VersionQuery { return &VersionQuery{b: versionTable.Query(db)} }

// VersionQuery is a query on the table of Version.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Version rows or a value; there is
// no way to run one without a Grant.
type VersionQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *VersionQuery) Base() *model.Builder { return q.b }

// New returns an empty Version on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *VersionQuery) New() (*Version, error) {
	e, err := q.b.NewModelInstance(nil)
	return versionOf(e), err
}

// VersionCollection is rows of Version, as a query returns them.
type VersionCollection []*Version

// VersionCollectionOf converts rows of the table of Version. A nil input is a nil
// collection.
func VersionCollectionOf(rows model.Rows) VersionCollection {
	if rows == nil {
		return nil
	}
	out := make(VersionCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Version)
	}
	return out
}

func versionOf(e model.Entity) *Version {
	row, _ := e.(*Version)
	return row
}

// versionColumn turns a closure over VersionQuery into one over the core builder, so
// passing func(*VersionQuery) where a column goes adds a parenthesised group.
func versionColumn(column any) any {
	if group, ok := column.(func(*VersionQuery)); ok {
		return func(b *model.Builder) { group(&VersionQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *VersionQuery) Clone() *VersionQuery { return &VersionQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*VersionQuery) in place of the column adds a group.
func (q *VersionQuery) Where(column any, args ...any) *VersionQuery {
	q.b.Where(versionColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*VersionQuery) in place of the column adds a group.
func (q *VersionQuery) OrWhere(column any, args ...any) *VersionQuery {
	q.b.OrWhere(versionColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *VersionQuery) WhereNot(column any, args ...any) *VersionQuery {
	q.b.WhereNot(versionColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *VersionQuery) OrWhereNot(column any, args ...any) *VersionQuery {
	q.b.OrWhereNot(versionColumn(column), args...)
	return q
}

func (q *VersionQuery) WhereIn(column any, values []any) *VersionQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *VersionQuery) WhereNotIn(column any, values []any) *VersionQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *VersionQuery) WhereNull(columns ...any) *VersionQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *VersionQuery) WhereNotNull(columns ...any) *VersionQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *VersionQuery) WhereBetween(column any, from, to any) *VersionQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *VersionQuery) WhereColumn(first any, args ...any) *VersionQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *VersionQuery) WhereKey(id any) *VersionQuery {
	q.b.WhereKey(id)
	return q
}

func (q *VersionQuery) WhereExists(callback func(*query.Builder)) *VersionQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *VersionQuery) WhereNotExists(callback func(*query.Builder)) *VersionQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *VersionQuery) WhereHas(relation string, callback func(*query.Builder)) *VersionQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *VersionQuery) OrWhereHas(relation string, callback func(*query.Builder)) *VersionQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *VersionQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *VersionQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *VersionQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *VersionQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *VersionQuery) WhereRelation(relation string, column any, args ...any) *VersionQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *VersionQuery) OrWhereRelation(relation string, column any, args ...any) *VersionQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *VersionQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *VersionQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *VersionQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *VersionQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *VersionQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *VersionQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *VersionQuery) OrHas(relation, operator string, count int) *VersionQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *VersionQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *VersionQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *VersionQuery) OrDoesntHave(relation string) *VersionQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *VersionQuery) Select(columns ...any) *VersionQuery {
	q.b.Select(columns...)
	return q
}

func (q *VersionQuery) AddSelect(columns ...any) *VersionQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *VersionQuery) SelectRaw(expression string, bindings ...any) *VersionQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *VersionQuery) Join(table any, first any, args ...any) *VersionQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *VersionQuery) GroupBy(groups ...any) *VersionQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *VersionQuery) OrderBy(column any, direction ...string) *VersionQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *VersionQuery) OrderByDesc(column any) *VersionQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *VersionQuery) Latest(column ...string) *VersionQuery {
	q.b.Latest(column...)
	return q
}

func (q *VersionQuery) Oldest(column ...string) *VersionQuery {
	q.b.Oldest(column...)
	return q
}

func (q *VersionQuery) Limit(value int) *VersionQuery {
	q.b.Limit(value)
	return q
}

func (q *VersionQuery) Offset(value int) *VersionQuery {
	q.b.Offset(value)
	return q
}

func (q *VersionQuery) ForPage(page, perPage int) *VersionQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *VersionQuery) With(relations ...string) *VersionQuery {
	q.b.With(relations...)
	return q
}

func (q *VersionQuery) WithCount(relations ...string) *VersionQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *VersionQuery) WithExists(relation string) *VersionQuery {
	q.b.WithExists(relation)
	return q
}

func (q *VersionQuery) WithSum(relation, column string) *VersionQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *VersionQuery) WithAvg(relation, column string) *VersionQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *VersionQuery) WithMin(relation, column string) *VersionQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *VersionQuery) WithMax(relation, column string) *VersionQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *VersionQuery) Without(relations ...string) *VersionQuery {
	q.b.Without(relations...)
	return q
}

func (q *VersionQuery) WithoutGlobalScope(identifier string) *VersionQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *VersionQuery) WithoutGlobalScopes(identifiers ...string) *VersionQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *VersionQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (VersionCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return VersionCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *VersionQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Version, error) {
	e, err := q.b.First(ctx, g, columns...)
	return versionOf(e), err
}

func (q *VersionQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Version, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return versionOf(e), err
}

func (q *VersionQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Version, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return versionOf(e), err
}

func (q *VersionQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Version, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return versionOf(e), err
}

func (q *VersionQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Version, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return versionOf(e), err
}

func (q *VersionQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Version, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return versionOf(e), err
}

func (q *VersionQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Version, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return versionOf(e), err
}

func (q *VersionQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Version, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return versionOf(e), err
}

func (q *VersionQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (VersionCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return VersionCollectionOf(rows), err
}

func (q *VersionQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Version, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return versionOf(e), err
}

func (q *VersionQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Version, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return versionOf(e), err
}

func (q *VersionQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Version, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return versionOf(e), err
}

func (q *VersionQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Version, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return versionOf(e), err
}

func (q *VersionQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (VersionCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return VersionCollectionOf(rows), meta, err
}

func (q *VersionQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (VersionCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return VersionCollectionOf(rows), meta, err
}

func (q *VersionQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (VersionCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return VersionCollectionOf(rows), meta, err
}

func (q *VersionQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(VersionCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(VersionCollectionOf(rows), page)
	})
}

func (q *VersionQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Version, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(versionOf(e), index)
	})
}

func (q *VersionQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Version, error] {
	return func(yield func(*Version, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(versionOf(e), err) {
				return
			}
		}
	}
}

func (q *VersionQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *VersionQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *VersionQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *VersionQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *VersionQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *VersionQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *VersionQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *VersionQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *VersionQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *VersionQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *VersionQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *VersionQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *VersionQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *VersionQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *VersionQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *VersionQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *VersionQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *VersionQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *VersionQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c VersionCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c VersionCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c VersionCollection) Find(key any) *Version { return versionOf(c.Rows().Find(key)) }

func (c VersionCollection) FindOrFail(key any) (*Version, error) {
	e, err := c.Rows().FindOrFail(key)
	return versionOf(e), err
}

func (c VersionCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c VersionCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c VersionCollection) Only(keys ...any) VersionCollection {
	return VersionCollectionOf(c.Rows().Only(keys...))
}

func (c VersionCollection) Except(keys ...any) VersionCollection {
	return VersionCollectionOf(c.Rows().Except(keys...))
}

func (c VersionCollection) Unique() VersionCollection { return VersionCollectionOf(c.Rows().Unique()) }

func (c VersionCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c VersionCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c VersionCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c VersionCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (VersionCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return VersionCollectionOf(rows), err
}

func (c VersionCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Version; it shadows the untyped one the
// embedded model promotes.
func (row *Version) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Version, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return versionOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Version) Replicate(except ...string) (*Version, error) {
	e, err := row.Model.Replicate(except...)
	return versionOf(e), err
}
